const PROVINCES = [
  "aceh",
  "kalimantan-timur",
  "jawa-barat",
  "jawa-tengah",
  "bengkulu",
  "banten",
  "jakarta-raya",
  "kalimantan-barat",
  "lampung",
  "sumatera-selatan",
  "bangka-belitung",
  "bali",
  "jawa-timur",
  "kalimantan-selatan",
  "nusa-tenggara-timur",
  "sulawesi-selatan",
  "sulawesi-barat",
  "kepulauan-riau",
  "gorontalo",
  "jambi",
  "kalimantan-tengah",
  "irian-jaya-barat",
  "sumatera-utara",
  "riau",
  "sulawesi-utara",
  "maluku-utara",
  "sumatera-barat",
  "yogyakarta",
  "maluku",
  "nusa-tenggara-barat",
  "sulawesi-tenggara",
  "sulawesi-tengah",
  "papua",
];

export default PROVINCES;
